MODEL:
  META_ARCHITECTURE: "SimpleBaseline"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  ROI_HEADS:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  ROI_MASK_HEAD:
    NAME: MaskRCNNConvUpsampleHead
    NUM_CONV: 4
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
  SimpleBaseline:
    NUM_QUERIES: 100
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.000025
  STEPS: (225000, 255000)
  MAX_ITER: 270000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
SEED: 40244023
INPUT:
  FORMAT: "RGB"
  MAX_SIZE_TRAIN: 1024
TEST:
  EVAL_PERIOD: 7330
DATALOADER:
  NUM_WORKERS: 4
VERSION: 2
