_BASE_: "Base-SimpleBaseline.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/swin/swin_base_patch4_window7_224_22k.pth"
  BACKBONE:
    NAME: "build_swin_base_fpn_backbone"
  SimpleBaseline:
    NUM_QUERIES: 100
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000

