_BASE_: "Base-SimpleBaseline.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_vit_base.pth"
  BACKBONE:
    NAME: "build_vitdet_base_backbone"
  SimpleBaseline:
    NUM_QUERIES: 100
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000

